= 2023

I started in C this year, mostly because I actually did this on my work laptop and was too lazy to setup Reason again..

== Day One:

- part 1: test values in an array for digits, sum them
-- this actually started out way more complex, but then I simplified the logic and it was straight forward.
- part 2: brute force scanning for number words over the set
-- if we have a digit, stop
-- if we have a word, stop
-- else move to the next position

== Day Two:

I ended up being too lazy to manage strings in C and just went with python

- part 1: split strings, constrain
- part 2: append a list, run `reduce(max, color_list, 0)` for each color, multiply and add to the `power`

= Day Three:

- part 1: every year I tell myself that next year I will have an adjacency matrix figured out before advent of code, but not this year...
-- make an adjacency matrix, and fill it int
- part 2: note whenever we see a gear, and then group all the gears together. if we have 2 part numbers by a gear, multiply them, and sum all of those
